import { Material } from "@/interfaces/Material";

export const materiais: Material[] = [
    {
        id: 'madeira-pinho',
        codigo: 'MAT-0001',
        nome: 'Madeira (Pinho)',
        descricao: 'Madeira de baixa densidade e boa trabalhabilidade, amplamente utilizada em estruturas leves, mobiliário e aplicações construtivas que exigem facilidade de corte e montagem.',
        categoria: 'Madeira',
        imagem: '/materiais/madeira.png',
        disponivel: true,
        resistencia: 40,
        densidade: 500,
        elasticidade: 9,
        dureza: 25,
        coeficientePoisson: 0.35,
        limiteEscoamento: 28,
        limiteRuptura: 40,
        alongamento: 3,
        aplicacoes: ['Móveis', 'Construção civil', 'Estruturas leves', 'Acabamentos'],
        cor: '#8B4513'
    },
    {
        id: 'aco-estrutural',
        codigo: 'MAT-0002',
        nome: 'Aço Estrutural',
        descricao: 'Liga metálica de alta resistência mecânica e elevada rigidez, empregada em estruturas sujeitas a grandes esforços de tração, compressão e flexão.',
        categoria: 'Metal',
        imagem: '/materiais/aco-estrutural.png',
        disponivel: true,
        resistencia: 400,
        densidade: 7850,
        elasticidade: 200,
        dureza: 75,
        coeficientePoisson: 0.30,
        limiteEscoamento: 250,
        limiteRuptura: 400,
        alongamento: 22,
        aplicacoes: ['Pontes', 'Vigas', 'Galpões', 'Máquinas industriais'],
        cor: '#71797E'
    },
    {
        id: 'concreto',
        codigo: 'MAT-0003',
        nome: 'Concreto',
        descricao: 'Material compósito formado por cimento, agregados e água, caracterizado por elevada resistência à compressão e ampla utilização em elementos estruturais da construção civil.',
        categoria: 'Cerâmico',
        imagem: '/materiais/concreto.png',
        disponivel: true,
        resistencia: 30,
        densidade: 2400,
        elasticidade: 17,
        dureza: 60,
        coeficientePoisson: 0.20,
        limiteEscoamento: 25,
        limiteRuptura: 30,
        alongamento: 0.2,
        aplicacoes: ['Fundações', 'Pilares', 'Lajes', 'Barragens'],
        cor: '#D3D3D3'
    },
    {
        id: 'aluminio',
        codigo: 'MAT-0004',
        nome: 'Alumínio',
        descricao: 'Metal leve com excelente resistência à corrosão, boa conformabilidade e alta relação resistência-peso, muito utilizado em transportes e estruturas leves.',
        categoria: 'Metal',
        imagem: '/materiais/aluminio.png',
        disponivel: true,
        resistencia: 110,
        densidade: 2700,
        elasticidade: 69,
        dureza: 45,
        coeficientePoisson: 0.33,
        limiteEscoamento: 95,
        limiteRuptura: 110,
        alongamento: 12,
        aplicacoes: ['Aeronaves', 'Esquadrias', 'Automóveis', 'Estruturas leves'],
        cor: '#D1D1D1'
    },
    {
        id: 'vidro',
        codigo: 'MAT-0005',
        nome: 'Vidro',
        descricao: 'Material cerâmico amorfo, transparente e rígido, com elevada resistência à compressão e aplicações em sistemas arquitetônicos, ópticos e decorativos.',
        categoria: 'Cerâmico',
        imagem: '/materiais/vidro.png',
        disponivel: true,
        resistencia: 50,
        densidade: 2500,
        elasticidade: 70,
        dureza: 70,
        coeficientePoisson: 0.22,
        limiteEscoamento: 45,
        limiteRuptura: 50,
        alongamento: 0.1,
        aplicacoes: ['Janelas', 'Fachadas', 'Lentes', 'Divisórias'],
        cor: '#A9D0F5'
    },
    {
        id: 'borracha',
        codigo: 'MAT-0006',
        nome: 'Borracha',
        descricao: 'Material elastomérico com alta capacidade de deformação elástica, absorção de impactos e amortecimento de vibrações, sendo amplamente utilizado em sistemas de vedação e isolamento.',
        categoria: 'Polímero',
        imagem: '/materiais/borracha.png',
        disponivel: true,
        resistencia: 15,
        densidade: 1100,
        elasticidade: 0.05,
        dureza: 10,
        coeficientePoisson: 0.49,
        limiteEscoamento: 10,
        limiteRuptura: 15,
        alongamento: 500,
        aplicacoes: ['Pneus', 'Vedações', 'Amortecedores', 'Isolamento'],
        cor: '#222222'
    },
    {
        id: 'titanio',
        codigo: 'MAT-0007',
        nome: 'Titânio',
        descricao: 'Metal de elevada resistência específica, combinando alta resistência mecânica, baixa densidade e excelente resistência à corrosão em ambientes agressivos.',
        categoria: 'Metal',
        imagem: '/materiais/titanio.png',
        disponivel: true,
        resistencia: 900,
        densidade: 4500,
        elasticidade: 110,
        dureza: 85,
        coeficientePoisson: 0.34,
        limiteEscoamento: 830,
        limiteRuptura: 900,
        alongamento: 15,
        aplicacoes: ['Aeronáutica', 'Implantes', 'Motores', 'Equipamentos navais'],
        cor: '#B2B2B2'
    },
    {
        id: 'cobre',
        codigo: 'MAT-0008',
        nome: 'Cobre',
        descricao: 'Metal não ferroso com excelente condutividade elétrica e térmica, amplamente empregado em instalações elétricas, componentes eletrônicos e sistemas de transferência de calor.',
        categoria: 'Metal',
        imagem: '/materiais/cobre.png',
        disponivel: true,
        resistencia: 220,
        densidade: 8960,
        elasticidade: 117,
        dureza: 35,
        coeficientePoisson: 0.34,
        limiteEscoamento: 70,
        limiteRuptura: 220,
        alongamento: 30,
        aplicacoes: ['Cabos elétricos', 'Tubulações', 'Motores', 'Eletrônicos'],
        cor: '#B87333'
    },
    {
        id: 'ouro',
        codigo: 'MAT-0009',
        nome: 'Ouro',
        descricao: 'Metal nobre altamente resistente à oxidação e corrosão, com elevada maleabilidade, ductilidade e excelente condutividade elétrica.',
        categoria: 'Metal',
        imagem: '/materiais/ouro.png',
        disponivel: true,
        resistencia: 100,
        densidade: 19300,
        elasticidade: 74,
        dureza: 20,
        coeficientePoisson: 0.44,
        limiteEscoamento: 80,
        limiteRuptura: 100,
        alongamento: 40,
        aplicacoes: ['Joias', 'Eletrônicos', 'Conectores', 'Revestimentos'],
        cor: '#FFD700'
    },
    {
        id: 'chumbo',
        codigo: 'MAT-0010',
        nome: 'Chumbo',
        descricao: 'Metal de alta densidade e elevada capacidade de absorção de radiação, frequentemente utilizado em blindagens, contrapesos e sistemas de armazenamento de energia.',
        categoria: 'Metal',
        imagem: '/materiais/chumbo.png',
        disponivel: true,
        resistencia: 12,
        densidade: 11340,
        elasticidade: 14,
        dureza: 5,
        coeficientePoisson: 0.44,
        limiteEscoamento: 10,
        limiteRuptura: 12,
        alongamento: 50,
        aplicacoes: ['Blindagem', 'Baterias', 'Contrapesos', 'Proteção radiológica'],
        cor: '#708090'
    },
    {
        id: 'plastico-abs',
        codigo: 'MAT-0011',
        nome: 'Plástico (ABS)',
        descricao: 'Polímero termoplástico que combina resistência ao impacto, boa estabilidade dimensional e facilidade de processamento, sendo amplamente utilizado em produtos industriais e de consumo.',
        categoria: 'Polímero',
        imagem: '/materiais/plastico.png',
        disponivel: true,
        resistencia: 40,
        densidade: 1050,
        elasticidade: 2.3,
        dureza: 30,
        coeficientePoisson: 0.39,
        limiteEscoamento: 35,
        limiteRuptura: 40,
        alongamento: 20,
        aplicacoes: ['Impressão 3D', 'Carcaças', 'Brinquedos', 'Automóveis'],
        cor: '#F0F0F0'
    },
    {
        id: 'fibra-carbono',
        codigo: 'MAT-0012',
        nome: 'Fibra de Carbono',
        descricao: 'Material compósito de altíssimo desempenho, caracterizado por elevada resistência mecânica, alta rigidez e baixa densidade, ideal para aplicações que exigem redução de peso.',
        categoria: 'Compósito',
        imagem: '/materiais/carbono.jpg',
        disponivel: true,
        resistencia: 3500,
        densidade: 1600,
        elasticidade: 230,
        dureza: 90,
        coeficientePoisson: 0.28,
        limiteEscoamento: 3200,
        limiteRuptura: 3500,
        alongamento: 1.5,
        aplicacoes: ['Aeronaves', 'Fórmula 1', 'Drones', 'Equipamentos esportivos'],
        cor: '#1C1C1C'
    },
    {
        id: 'diamante',
        codigo: 'MAT-0013',
        nome: 'Diamante',
        descricao: 'Estrutura cristalina de carbono reconhecida por possuir a maior dureza natural conhecida, além de elevada rigidez e excelente resistência ao desgaste.',
        categoria: 'Cristalino',
        imagem: '/materiais/diamante.png',
        disponivel: true,
        resistencia: 1600,
        densidade: 3510,
        elasticidade: 1220,
        dureza: 100,
        coeficientePoisson: 0.10,
        limiteEscoamento: 1500,
        limiteRuptura: 1600,
        alongamento: 0.05,
        aplicacoes: ['Ferramentas de corte', 'Perfuração', 'Joias', 'Polimento'],
        cor: '#E0FFFF'
    },
    {
        id: 'latao',
        codigo: 'MAT-0014',
        nome: 'Latão',
        descricao: 'Liga metálica composta principalmente por cobre e zinco, oferecendo boa resistência mecânica, resistência à corrosão e excelente usinabilidade.',
        categoria: 'Metal',
        imagem: '/materiais/latao.png',
        disponivel: true,
        resistencia: 250,
        densidade: 8500,
        elasticidade: 110,
        dureza: 55,
        coeficientePoisson: 0.34,
        limiteEscoamento: 180,
        limiteRuptura: 250,
        alongamento: 20,
        aplicacoes: ['Válvulas', 'Conexões', 'Instrumentos', 'Decoração'],
        cor: '#B5A642'
    },
    {
        id: 'granito',
        codigo: 'MAT-0015',
        nome: 'Granito',
        descricao: 'Rocha ígnea natural de elevada dureza, resistência ao desgaste e durabilidade, amplamente empregada em revestimentos, pisos e elementos arquitetônicos.',
        categoria: 'Rocha',
        imagem: '/materiais/granito.png',
        disponivel: true,
        resistencia: 200,
        densidade: 2700,
        elasticidade: 50,
        dureza: 80,
        coeficientePoisson: 0.25,
        limiteEscoamento: 180,
        limiteRuptura: 200,
        alongamento: 0.2,
        aplicacoes: ['Bancadas', 'Pisos', 'Monumentos', 'Revestimentos'],
        cor: '#696969'
    }
]
